"""inicial

Revision ID: 737d9a85a650
Revises: 
Create Date: 2026-09-22 22:49:30.127571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737d9a85a650'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agrupaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activa', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('instrumentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('familia', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tokens_bloqueados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tokens_bloqueados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_bloqueados_jti'), ['jti'], unique=True)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('password_set', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.Column('password_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('requiere_cambio_clave', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_cedula'), ['cedula'], unique=True)

    op.create_table('alumnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('nombre_representante', sa.String(length=160), nullable=True),
    sa.Column('telefono_representante', sa.String(length=20), nullable=True),
    sa.Column('nivel_academico', sa.String(length=80), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('convocatorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('activa', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('creada_por', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creada_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos_cronograma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agrupacion_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('lugar', sa.String(length=200), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('notificar_cambios', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('mensaje_alerta', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['agrupacion_id'], ['agrupaciones.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eventos_cronograma', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eventos_cronograma_agrupacion_id'), ['agrupacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eventos_cronograma_fecha_inicio'), ['fecha_inicio'], unique=False)

    op.create_table('partituras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('obra', sa.String(length=150), nullable=True),
    sa.Column('compositor', sa.String(length=150), nullable=True),
    sa.Column('catedra', sa.String(length=80), nullable=True),
    sa.Column('agrupacion_id', sa.Integer(), nullable=False),
    sa.Column('instrumento_id', sa.Integer(), nullable=True),
    sa.Column('archivo_nombre', sa.String(length=300), nullable=False),
    sa.Column('archivo_ruta', sa.String(length=500), nullable=False),
    sa.Column('subido_por', sa.Integer(), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['agrupacion_id'], ['agrupaciones.id'], ),
    sa.ForeignKeyConstraint(['instrumento_id'], ['instrumentos.id'], ),
    sa.ForeignKeyConstraint(['subido_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('codigo_hash', sa.String(length=64), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('intentos', sa.Integer(), server_default='0', nullable=False),
    sa.Column('usado', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_codes_codigo_hash'), ['codigo_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_codes_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('profesores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('usuario_agrupacion',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('agrupacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agrupacion_id'], ['agrupaciones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'agrupacion_id')
    )
    op.create_table('alumno_instrumento',
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('instrumento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['instrumento_id'], ['instrumentos.id'], ),
    sa.PrimaryKeyConstraint('alumno_id', 'instrumento_id')
    )
    op.create_table('asistencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('agrupacion_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.CheckConstraint("estado IN ('presente','ausente','justificado','retraso')", name='ck_asistencia_estado'),
    sa.ForeignKeyConstraint(['agrupacion_id'], ['agrupaciones.id'], ),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alumno_id', 'agrupacion_id', 'fecha', name='uq_asistencia_dia')
    )
    with op.batch_alter_table('asistencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asistencias_agrupacion_id'), ['agrupacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asistencias_alumno_id'), ['alumno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asistencias_fecha'), ['fecha'], unique=False)

    op.create_table('aspirantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('convocatoria_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('instrumento_postulado', sa.String(length=80), nullable=True),
    sa.Column('experiencia_previa', sa.Text(), nullable=True),
    sa.Column('video_nombre', sa.String(length=300), nullable=True),
    sa.Column('video_ruta', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default='pendiente', nullable=False),
    sa.Column('inscrito_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['convocatoria_id'], ['convocatorias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('convocatoria_id', 'cedula', name='uq_aspirante_convocatoria_cedula')
    )
    with op.batch_alter_table('aspirantes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aspirantes_cedula'), ['cedula'], unique=False)
        batch_op.create_index(batch_op.f('ix_aspirantes_convocatoria_id'), ['convocatoria_id'], unique=False)

    op.create_table('audiciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('convocatoria_id', sa.Integer(), nullable=True),
    sa.Column('agrupacion_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('lugar', sa.String(length=200), nullable=True),
    sa.Column('jurado_ids', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['agrupacion_id'], ['agrupaciones.id'], ),
    sa.ForeignKeyConstraint(['convocatoria_id'], ['convocatorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profesor_agrupacion',
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.Column('agrupacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agrupacion_id'], ['agrupaciones.id'], ),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesores.id'], ),
    sa.PrimaryKeyConstraint('profesor_id', 'agrupacion_id')
    )
    op.create_table('audicion_jurado',
    sa.Column('audicion_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audicion_id'], ['audiciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('audicion_id', 'usuario_id')
    )
    op.create_table('puntuaciones_audicion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aspirante_id', sa.Integer(), nullable=False),
    sa.Column('jurado_id', sa.Integer(), nullable=False),
    sa.Column('tecnica', sa.Float(), nullable=True),
    sa.Column('interpretacion', sa.Float(), nullable=True),
    sa.Column('afinacion', sa.Float(), nullable=True),
    sa.Column('ritmo', sa.Float(), nullable=True),
    sa.Column('presencia', sa.Float(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('puntuacion_total', sa.Float(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.CheckConstraint('afinacion >= 0 AND afinacion <= 10', name='ck_punt_afinacion'),
    sa.CheckConstraint('interpretacion >= 0 AND interpretacion <= 10', name='ck_punt_interpretacion'),
    sa.CheckConstraint('presencia >= 0 AND presencia <= 10', name='ck_punt_presencia'),
    sa.CheckConstraint('ritmo >= 0 AND ritmo <= 10', name='ck_punt_ritmo'),
    sa.CheckConstraint('tecnica >= 0 AND tecnica <= 10', name='ck_punt_tecnica'),
    sa.ForeignKeyConstraint(['aspirante_id'], ['aspirantes.id'], ),
    sa.ForeignKeyConstraint(['jurado_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aspirante_id', 'jurado_id', name='uq_puntuacion_jurado')
    )
    with op.batch_alter_table('puntuaciones_audicion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_puntuaciones_audicion_aspirante_id'), ['aspirante_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_puntuaciones_audicion_jurado_id'), ['jurado_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puntuaciones_audicion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_puntuaciones_audicion_jurado_id'))
        batch_op.drop_index(batch_op.f('ix_puntuaciones_audicion_aspirante_id'))

    op.drop_table('puntuaciones_audicion')
    op.drop_table('audicion_jurado')
    op.drop_table('profesor_agrupacion')
    op.drop_table('audiciones')
    with op.batch_alter_table('aspirantes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aspirantes_convocatoria_id'))
        batch_op.drop_index(batch_op.f('ix_aspirantes_cedula'))

    op.drop_table('aspirantes')
    with op.batch_alter_table('asistencias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asistencias_fecha'))
        batch_op.drop_index(batch_op.f('ix_asistencias_alumno_id'))
        batch_op.drop_index(batch_op.f('ix_asistencias_agrupacion_id'))

    op.drop_table('asistencias')
    op.drop_table('alumno_instrumento')
    op.drop_table('usuario_agrupacion')
    op.drop_table('profesores')
    with op.batch_alter_table('password_reset_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_codes_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_codes_codigo_hash'))

    op.drop_table('password_reset_codes')
    op.drop_table('partituras')
    with op.batch_alter_table('eventos_cronograma', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eventos_cronograma_fecha_inicio'))
        batch_op.drop_index(batch_op.f('ix_eventos_cronograma_agrupacion_id'))

    op.drop_table('eventos_cronograma')
    op.drop_table('convocatorias')
    op.drop_table('alumnos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_cedula'))

    op.drop_table('usuarios')
    with op.batch_alter_table('tokens_bloqueados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_bloqueados_jti'))

    op.drop_table('tokens_bloqueados')
    op.drop_table('instrumentos')
    op.drop_table('agrupaciones')
    # ### end Alembic commands ###
